<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ...
        DB::table('barangs')->insert([
            [
                'id_penitip' => 1,
                'id_kategori' => 1,
                'id_pegawai' => 3,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(30),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Smartphone',
                'harga_barang' => 2500000,
                'berat_barang' => 500,
                'deskripsi' => 'Barang Oke',
                'status_garansi' => now()->copy()->addDays(10),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/smartphone.jpg',
                'gambar_dua' => 'images/barang/smartphone.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 2,
                'id_pegawai' => 3,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Pakaian Pria',
                'harga_barang' => 50000,
                'berat_barang' => 2,
                'deskripsi' => 'Ukuran XL',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/pakaianPria.jpeg',
                'gambar_dua' => 'images/barang/pakaianPria.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 3,
                'id_pegawai' => 3,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(15),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Test',
                'harga_barang' => 10000,
                'berat_barang' => 20,
                'deskripsi' => 'Test Deskripsi',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/pakaianPria.jpeg',
                'gambar_dua' => 'images/barang/pakaianPria.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 3,
                'id_kategori' => 3,
                'id_pegawai' => 3,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(20),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Meja Belajar',
                'harga_barang' => 150000,
                'berat_barang' => 50,
                'deskripsi' => 'Kayu Jati',
                'status_garansi' => now()->copy()->addDays(12),
                'status_barang' => 'Tersedia',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/meja.jpeg',
                'gambar_dua' => 'images/barang/meja.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 4,
                'id_kategori' => 4,
                'id_pegawai' => 6,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(30),
                'penambahan_durasi' => 1,
                'nama_barang' => 'Buku Pelajaran',
                'harga_barang' => 20000,
                'berat_barang' => 1,
                'deskripsi' => 'Halaman Lebih Banyak',
                'status_garansi' => null,
                'status_barang' => 'Tersedia',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/buku.jpeg',
                'gambar_dua' => 'images/barang/buku.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 5,
                'id_kategori' => 5,
                'id_pegawai' => 6,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(30),
                'penambahan_durasi' => 1,
                'nama_barang' => 'Boneka Teddy Bear',
                'harga_barang' => 250000,
                'berat_barang' => 1,
                'deskripsi' => 'Mainan Anak',
                'status_garansi' => now()->copy()->addDays(6),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/mainan.jpeg',
                'gambar_dua' => 'images/barang/mainan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 6,
                'id_kategori' => 6,
                'id_pegawai' => 6,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(1),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Kereta Bayi',
                'harga_barang' => 45000,
                'berat_barang' => 10,
                'deskripsi' => 'Untuk Balita',
                'status_garansi' => now()->copy()->addDays(18),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/keretabayi.jpeg',
                'gambar_dua' => 'images/barang/keretabayi.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 7,
                'id_kategori' => 7,
                'id_pegawai' => 9,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Sepeda Motor Beat 2018',
                'harga_barang' => 2500000,
                'berat_barang' => 500,
                'deskripsi' => 'Mesin Oke',
                'status_garansi' => now()->copy()->addDays(19),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/motor.jpeg',
                'gambar_dua' => 'images/barang/motor.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 8,
                'id_kategori' => 8,
                'id_pegawai' => 9,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Cangkul Taman',
                'harga_barang' => 40000,
                'berat_barang' => 5,
                'deskripsi' => 'Untuk Berkebun',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/cangkul.jpeg',
                'gambar_dua' => 'images/barang/cangkul.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 9,
                'id_kategori' => 9,
                'id_pegawai' => 9,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(2),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Mesin Fotokopi',
                'harga_barang' => 400000,
                'berat_barang' => 800,
                'deskripsi' => 'Free tinta 3 warna',
                'status_garansi' => now()->copy()->addDays(12),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/fotocopy.jpeg',
                'gambar_dua' => 'images/barang/fotocopy.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 10,
                'id_kategori' => 10,
                'id_pegawai' => 9,
                'id_hunter' => 13,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(3),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Parfum',
                'harga_barang' => 20000,
                'berat_barang' => 1,
                'deskripsi' => 'Wangi Tahan Lama',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/parfum.jpeg',
                'gambar_dua' => 'images/barang/parfum.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 11,
                'id_kategori' => 11,
                'id_pegawai' => 10,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(15),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Tas Sekolah',
                'harga_barang' => 0,
                'berat_barang' => 2,
                'deskripsi' => 'Kondisi baik, cocok untuk anak SD',
                'status_garansi' => null,
                'status_barang' => 'barang untuk Donasi',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/tas.jpeg',
                'gambar_dua' => 'images/barang/tas.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 12,
                'id_kategori' => 3,
                'id_pegawai' => 10,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(20),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Jaket Hangat',
                'harga_barang' => 0,
                'berat_barang' => 1,
                'deskripsi' => 'Masih layak pakai, cocok untuk musim hujan',
                'status_garansi' => null,
                'status_barang' => 'barang untuk Donasi',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/jaket.jpeg',
                'gambar_dua' => 'images/barang/jaket.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 13,
                'id_kategori' => 4,
                'id_pegawai' => 10,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(10),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Buku Cerita Anak',
                'harga_barang' => 0,
                'berat_barang' => 1,
                'deskripsi' => 'Isi lengkap, halaman utuh, edukatif',
                'status_garansi' => null,
                'status_barang' => 'barang untuk Donasi',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/bukuanak.jpeg',
                'gambar_dua' => 'images/barang/bukuanak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
