<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */


    public function run(): void
    {
        // ...
        DB::table('barangs')->insert([
            //

            [
                'id_penitip' => 1,
                'id_kategori' => 1,
                'id_pegawai' => 3,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(1)->addMinutes(2), // <= ini bagian penting
                'penambahan_durasi' => 0,
                'nama_barang' => 'Smartphone',
                'harga_barang' => 2500000,
                'berat_barang' => 500,
                'deskripsi' => 'Barang Oke',
                'status_garansi' => now()->copy()->addDays(10),
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/smartphone.jpg',
                'gambar_dua' => 'images/barang/smartphone.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_penitip' => 2,
                'id_kategori' => 2,
                'id_pegawai' => 3,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Pakaian Pria',
                'harga_barang' => 50000,
                'berat_barang' => 2,
                'deskripsi' => 'Ukuran XL',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/pakaianPria.jpeg',
                'gambar_dua' => 'images/barang/pakaianPria.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 3,
                'id_pegawai' => 3,
                'id_hunter' => 14,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(15),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Test',
                'harga_barang' => 12000,
                'berat_barang' => 20,
                'deskripsi' => 'Test Deskripsi',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/pakaianPria.jpeg',
                'gambar_dua' => 'images/barang/pakaianPria.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 2,
                'id_pegawai' => 3,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 1,
                'nama_barang' => 'Pakaian Wanita',
                'harga_barang' => 500000,
                'berat_barang' => 2,
                'deskripsi' => 'Ukuran XL',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/pakaianPria.jpeg',
                'gambar_dua' => 'images/barang/pakaianPria.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 3,
                'id_pegawai' => 3,
                'id_hunter' => 14,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Pakain Anak',
                'harga_barang' => 100000,
                'berat_barang' => 20,
                'deskripsi' => 'Test Deskripsi',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/pakaianPria.jpeg',
                'gambar_dua' => 'images/barang/pakaianPria.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 3,
                'id_kategori' => 3,
                'id_pegawai' => 3,
                'id_hunter' => 15,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(20),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Meja Belajar',
                'harga_barang' => 150000,
                'berat_barang' => 50,
                'deskripsi' => 'Kayu Jati',
                'status_garansi' => now()->copy()->addDays(12),
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/meja.jpeg',
                'gambar_dua' => 'images/barang/meja.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 4,
                'id_kategori' => 4,
                'id_pegawai' => 6,
                'id_hunter' => 14,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(30),
                'penambahan_durasi' => 1,
                'nama_barang' => 'Buku Pelajaran',
                'harga_barang' => 20000,
                'berat_barang' => 1,
                'deskripsi' => 'Halaman Lebih Banyak',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/buku.jpeg',
                'gambar_dua' => 'images/barang/buku.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 5,
                'id_kategori' => 5,
                'id_pegawai' => 6,
                'id_hunter' => 15,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(30),
                'penambahan_durasi' => 1,
                'nama_barang' => 'Boneka Teddy Bear',
                'harga_barang' => 250000,
                'berat_barang' => 1,
                'deskripsi' => 'Mainan Anak',
                'status_garansi' => now()->copy()->addDays(6),
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/mainan.jpeg',
                'gambar_dua' => 'images/barang/mainan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 6,
                'id_kategori' => 6,
                'id_pegawai' => 6,
                'id_hunter' => 15,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(-1),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Kereta Bayi',
                'harga_barang' => 45000,
                'berat_barang' => 10,
                'deskripsi' => 'Untuk Balita',
                'status_garansi' => now()->copy()->addDays(18),
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/keretabayi.jpeg',
                'gambar_dua' => 'images/barang/keretabayi.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 7,
                'id_kategori' => 7,
                'id_pegawai' => 9,
                'id_hunter' => 15,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Sepeda Motor Beat 2018',
                'harga_barang' => 2500000,
                'berat_barang' => 500,
                'deskripsi' => 'Mesin Oke',
                'status_garansi' => now()->copy()->addDays(19),
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/motor.jpeg',
                'gambar_dua' => 'images/barang/motor.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 8,
                'id_kategori' => 8,
                'id_pegawai' => 9,
                'id_hunter' => 15,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(0),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Cangkul Taman',
                'harga_barang' => 40000,
                'berat_barang' => 5,
                'deskripsi' => 'Untuk Berkebun',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/cangkul.jpeg',
                'gambar_dua' => 'images/barang/cangkul.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 9,
                'id_kategori' => 9,
                'id_pegawai' => 9,
                'id_hunter' => 14,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(2),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Mesin Fotokopi',
                'harga_barang' => 400000,
                'berat_barang' => 800,
                'deskripsi' => 'Free tinta 3 warna',
                'status_garansi' => now()->copy()->addDays(12),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/fotocopy.jpeg',
                'gambar_dua' => 'images/barang/fotocopy.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 10,
                'id_kategori' => 10,
                'id_pegawai' => 9,
                'id_hunter' => 14,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(3),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Parfum',
                'harga_barang' => 20000,
                'berat_barang' => 1,
                'deskripsi' => 'Wangi Tahan Lama',
                'status_garansi' => null,
                'status_barang' => 'Sold Out',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/parfum.jpeg',
                'gambar_dua' => 'images/barang/parfum.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 3,
                'id_pegawai' => 10,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(15),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Tas Sekolah',
                'harga_barang' => 0,
                'berat_barang' => 2,
                'deskripsi' => 'Kondisi baik, cocok untuk anak SD',
                'status_garansi' => null,
                'status_barang' => 'barang untuk Donasi',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/tas.jpeg',
                'gambar_dua' => 'images/barang/tas.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 3,
                'id_pegawai' => 10,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(20),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Jaket Hangat',
                'harga_barang' => 0,
                'berat_barang' => 1,
                'deskripsi' => 'Masih layak pakai, cocok untuk musim hujan',
                'status_garansi' => null,
                'status_barang' => 'barang untuk Donasi',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/jaket.jpeg',
                'gambar_dua' => 'images/barang/jaket.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penitip' => 2,
                'id_kategori' => 4,
                'id_pegawai' => 10,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(10),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Buku Cerita Anak',
                'harga_barang' => 0,
                'berat_barang' => 1,
                'deskripsi' => 'Isi lengkap, halaman utuh, edukatif',
                'status_garansi' => null,
                'status_barang' => 'barang untuk Donasi',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/bukuanak.jpeg',
                'gambar_dua' => 'images/barang/bukuanak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // untuk laporan
            [
                'id_penitip' => 1,
                'id_kategori' => 1,
                'id_pegawai' => 10,
                'id_hunter' => 15,
                'tgl_penitipan' => now()->subDays(30),
                'masa_penitipan' => now(),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Laptop Acer',
                'harga_barang' => 2500000,
                'berat_barang' => 1,
                'deskripsi' => 'Barang oke',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/laptop.jpeg',
                'gambar_dua' => 'images/barang/laptop1.jpeg',
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(30),
            ],

            [
                'id_penitip' => 3,
                'id_kategori' => 5,
                'id_pegawai' => 10,
                'id_hunter' => 14,
                'tgl_penitipan' => now()->subDays(30),
                'masa_penitipan' => now(),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Mainan Anak Kecil Bos',
                'harga_barang' => 17000,
                'berat_barang' => 1,
                'deskripsi' => 'Barang oke',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/mainan.jpeg',
                'gambar_dua' => 'images/barang/mobil.jpeg',
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(30),
            ],

            [
                'id_penitip' => 3,
                'id_kategori' => 7,
                'id_pegawai' => 10,
                'id_hunter' => 14,
                'tgl_penitipan' => now()->subDays(30),
                'masa_penitipan' => now(),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Mobil Avanza',
                'harga_barang' => 5000000,
                'berat_barang' => 1,
                'deskripsi' => 'Barang oke',
                'status_garansi' => null,
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/kijang.jpeg',
                'gambar_dua' => 'images/barang/mobil.jpeg',
                'created_at' => now()->subDays(25),
                'updated_at' => now()->subDays(25),
            ],

        ]);

        $staticData = [
            [
                'id_penitip' => 1,
                'id_kategori' => 1,
                'id_pegawai' => 3,
                'id_hunter' => null,
                'tgl_penitipan' => now(),
                'masa_penitipan' => now()->copy()->addDays(30),
                'penambahan_durasi' => 0,
                'nama_barang' => 'Smartphone',
                'harga_barang' => 2500000,
                'berat_barang' => 500,
                'deskripsi' => 'Barang Oke',
                'status_garansi' => now()->copy()->addDays(10),
                'status_barang' => 'Dijual',
                'tgl_pengambilan' => null,
                'gambar' => 'images/barang/smartphone.jpg',
                'gambar_dua' => 'images/barang/smartphone.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tambah data manual lain kalau perlu
        ];

        // Generate 200 data acak
        $dummyData = $this->generateDummyData(200);

        DB::table('barangs')->insert(array_merge($staticData, $dummyData));
        // DB::table('barangs')->insert($staticData);
    }

    protected function randomDateThisYear()
    {
        $start = strtotime(date('Y') . '-01-01');
        $end = strtotime(date('Y') . '-12-31');
        return date('Y-m-d', rand($start, $end));
    }

    protected function generateDummyData($jumlah = 200)
    {
        $statusList = ['barang untuk donasi', 'Dijual', 'penitip habis', 'Sold Out'];
        $pegawaiList = [3, 6, 9];
        $gambarList = [
            'images/barang/buku.jpeg',
            'images/barang/cangkul.jpeg',
            'images/barang/fotocopy.jpeg',
            'images/barang/keretabayi.jpeg',
            'images/barang/mainan.jpeg',
            'images/barang/meja.jpeg',
            'images/barang/motor.jpeg',
        ];

        $data = [];

        for ($i = 0; $i < $jumlah; $i++) {
            $tglPenitipan = $this->randomDateThisYear();
            $masaHari = rand(0, 30);
            $masaPenitipan = date('Y-m-d', strtotime("+$masaHari days", strtotime($tglPenitipan)));
            $gambar = $gambarList[array_rand($gambarList)];
            $status = $statusList[array_rand($statusList)];
            $idPegawai = $pegawaiList[array_rand($pegawaiList)];

            $data[] = [
                'id_penitip' => rand(1, 10),
                'id_kategori' => rand(1, 10),
                'id_pegawai' => $idPegawai,
                'id_hunter' => null,
                'tgl_penitipan' => $tglPenitipan,
                'masa_penitipan' => $masaPenitipan,
                'penambahan_durasi' => rand(0, 2),
                'nama_barang' => 'Barang Dummy ' . ($i + 1),
                'harga_barang' => rand(0, 1) ? rand(10000, 1000000) : 0,
                'berat_barang' => rand(1, 5),
                'deskripsi' => 'Deskripsi dummy ' . ($i + 1),
                'status_garansi' => null,
                'status_barang' => $status,
                'tgl_pengambilan' => null,
                'gambar' => $gambar,
                'gambar_dua' => $gambar,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        return $data;
    }
}
